FROM ubuntu:latest

RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "vim"]
RUN ["apt-get", "install", "build-essential", "-y"]

CMD echo "Created new docker from ubuntu image!"; echo "Installed vim and build-essential in it!"
